[tools]
rust = "1.92.0"
watchexec = "latest"

[tasks.configure-git]
description="Easy git configuration for this project."
quiet=true
silent=true
run = '''
git config pull.ff only
git config merge.ff false
'''
sources=[".git/config"]

[tasks.develop]
description="Head task for setting up development"
depends=["configure-git"]

[tasks.build]
depends=["develop"]